version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    depends_on:
      - tests
  tests:
    build:
      context: .
      dockerfile: Dockerfile_dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]